name: Documentation Deployment

env:
  LANA_OPENAI_API_KEY: ${{ vars.LANA_OPENAI_API_KEY }}
  LANA_MODEL: ${{ vars.LANA_MODEL }}
  
on:
  push:
    branches:
      - main
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

  generate-and-deploy:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate documentation
        run: |
          cd docs-beta
          npm install -g yargs
          npm install -g lanadoc-cli
          echo $LANA_OPENAI_API_KEY
          echo $LANA_MODEL
          lanadoc config --set LANA_OPENAI_API_KEY=$LANA_OPENAI_API_KEY
          lanadoc config --set LANA_MODEL=$LANA_MODEL
          lanadoc generate
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

      - name: Validate openapi specification
        run: echo "lanadoc validate"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/output
          publish_branch: gh-pages
