name: Documentation Deployment

on:
  push:
    branches:
      - main
      - production
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g lanadoc-cli

  generate-and-deploy:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate documentation
        run: |
          cd docs
          lanadoc generate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANA_MODEL: ${{ secrets.LANA_MODEL }}
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production' || github.ref == 'refs/heads/develop'

      - name: Validate openapi specification
        run: echo "lanadoc validate"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/output
          publish_branch: gh-pages

      - name: Deploy developer demo (optional)
        if: github.ref == 'refs/heads/develop'
        run: echo "Deploying developer demo..."
